name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/dependency-review.yml@main

  security-analysis:
    name: Security Analysis
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/brakeman.yml@main
    secrets: inherit
    permissions:
      contents: read
      security-events: write
      actions: read

  lint-ruby:
    name: Lint Ruby
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          bundler-cache: true

      - name: Run RSpec
        env:
          RAILS_ENV: test
          # All Google client library calls are mocked, but the application needs this set to boot
          GOOGLE_CLOUD_PROJECT_ID: not-used
          GOOGLE_CLOUD_PROJECT_ID_NUMBER: not-used
          DISCOVERY_ENGINE_DEFAULT_COLLECTION_NAME: not-used
          DISCOVERY_ENGINE_DEFAULT_LOCATION_NAME: not-used      
          REDIS_URL: redis://localhost:6379 # not used in tests, but required to boot the application
        run: bundle exec rake spec