name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

jobs:
  security-analysis:
    name: Security Analysis
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/brakeman.yml@main
    secrets: inherit
    permissions:
      contents: read
      security-events: write
      actions: read

  lint-ruby:
    name: Lint Ruby
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4               

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RSpec
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-postgres.outputs.db-url }}
        run: bundle exec rake spec